#!/usr/bin/env bash

# Save current directory
OLDDIR=`pwd`
cygwin=false
case "`uname`" in
  CYGWIN*) cygwin=true;;
esac

# Set the current directory to the installation directory
INSTALLDIR=`dirname "$PRG"`
cd "$INSTALLDIR"

# Use JAVA_HOME if it is set
if [ -z "$JAVA_HOME" ]; then
 JAVA_CMD=java
else
 JAVA_CMD=$JAVA_HOME/bin/java
fi

CP="./confman-command-${project.version}.jar"

if $cygwin; then
  CP=$(cygpath -pw "$CP")
fi

"$JAVA_CMD" -jar "$CP"

# Save the exit code
JAVA_EXIT_CODE=$?

# Restore current directory
cd "$OLDDIR"

# Exit using the same code returned from Java
exit $JAVA_EXIT_CODE